workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.simpleviralgames.timepass"

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build Android release
        script: |
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")

          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
              # fallback in case no build number was found
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi

          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER

    artifacts:
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false

      slack:
        channel: "#your-slack-channel"  # Change to your actual Slack channel name
        notify_on_build_start: false
        notify:
          success: true
          failure: true
        webhook_url: $SLACK_WEBHOOK_URL

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

    # Custom step to notify with test link
    post_publish_scripts:
      - name: Notify Slack with internal testing link
        script: |
          TEST_LINK="https://play.google.com/apps/testing/$PACKAGE_NAME"
          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"text\": \"✅ *Build succeeded and uploaded to Google Play Internal Track!*\nTesters can access it here: <$TEST_LINK>\"
            }" $SLACK_WEBHOOK_URL
