workflows:
  print-version-info:
    name: Print Android Version Info
    max_build_duration: 10
    instance_type: mac_mini_m2

    scripts:
      - name: Extract and print version info
        script: |
          cd $CM_BUILD_DIR
          echo "📁 Listing project structure:"
          find . -type f -name "build.gradle.kts" || echo "No build.gradle files found."
