workflows:
  build-and-upload-aab:
    name: Build & Upload AAB
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      android_signing:
        - my-uploaded-keystore  # Replace with your keystore ID
      groups:
        - google_play            # Enables Play Store access
        - slack_credentials      # For Slack Webhook

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Debug signing environment
        script: |
          echo "Keystore Path: $CM_KEYSTORE_PATH"
          echo "Alias: $CM_KEY_ALIAS"

      - name: Build signed release AAB
        script: |
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.aab

    publishing:
#      google_play:
#        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
#        track: internal
#        submit_as_draft: false

      slack:
        channel: '#codemagic'                 # ← required
        notify_on_build_start: false     # optional
        notify:
          success: true
          failure: true
