workflows:
  build-apk:
    name: Build APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      # Reference the variable group "test"
      variable_group: test  # This links the environment variables from the "test" variable group

      android_signing:
        - keystore_reference  # Your keystore environment variable

    vars:
      PACKAGE_NAME: "com.simpleviralgames.timepass"
      # Additional variables if needed

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build signed release APK
        script: |
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
