workflows:
  build-apk:
    name: Build APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.simpleviralgames.timepass"

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Build signed release APK
        script: |
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
