workflows:
  print-version-info:
    name: Print Android Version Info
    max_build_duration: 10
    instance_type: mac_mini_m2

    scripts:
      - name: Extract and print version info
        script: |
          cd $CM_BUILD_DIR

          if [ -f "app/build.gradle" ]; then
            VERSION_CODE=$(grep -m 1 "versionCode" app/build.gradle | awk '{print $2}' | tr -d ';')
            VERSION_NAME=$(grep -m 1 "versionName" app/build.gradle | awk '{print $2}' | tr -d '"')
          else
            echo "Error: app/build.gradle not found!"
            exit 1
          fi

          if [ -z "$VERSION_CODE" ]; then
            echo "Error: versionCode not found!"
            exit 1
          fi

          if [ -z "$VERSION_NAME" ]; then
            echo "Error: versionName not found!"
            exit 1
          fi

          echo "✅ Version Code: $VERSION_CODE"
          echo "✅ Version Name: $VERSION_NAME"
