workflows:
  build-aab:
    name: Build AAB
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      android_signing:
        - keystore_reference  # Ensure this matches your Codemagic keystore ID

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Debug signing environment
        script: |
          echo "Keystore Path: $CM_KEYSTORE_PATH"
          echo "Alias: $CM_KEY_ALIAS"

      - name: Build signed release AAB
        script: |
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.aab
